# Entrenamiento 2

**Análisis de Datos – Sector Salud**

En este ejercicio trabajarás con un dataset ficticio del sector salud. Sigue las instrucciones y responde las preguntas planteadas. No incluyas las respuestas en este archivo.

In [2]:
import pandas as pd
import numpy as np

# Dataset ficticio de pacientes
data = {
    "id_paciente": range(1, 31),
    "edad": np.random.randint(18, 80, 30),
    "genero": np.random.choice(["F", "M"], 30),
    "dias_hospitalizado": np.random.randint(1, 20, 30),
    "costo_tratamiento": np.random.randint(5000, 80000, 30),
    "reingreso_30_dias": np.random.choice([0, 1], 30)
}

df = pd.DataFrame(data)
df

,id_paciente,edad,genero,dias_hospitalizado,costo_tratamiento,reingreso_30_dias
0,1,25,M,2,72971,0
1,2,75,F,5,43590,0
2,3,74,M,14,22379,0
3,4,25,F,15,30350,1
4,5,19,M,13,65172,1
5,6,65,F,18,65709,1
6,7,73,M,13,28499,0
7,8,70,M,10,59259,1
8,9,57,M,13,34741,0
9,10,49,M,3,22848,0
10,11,58,M,1,54924,0
11,12,74,F,14,25457,0
12,13,64,M,16,77751,0
13,14,55,M,13,27221,0
14,15,42,F,16,32996,1
15,16,79,F,8,16435,0
16,17,41,F,10,5408,0
17,18,20,F,10,41170,0
18,19,28,F,10,28614,1
19,20,76,M,8,13140,0
20,21,69,F,11,17366,0
21,22,30,M,1,53320,0
22,23,46,F,1,59104,1
23,24,28,F,17,13094,1
24,25,61,F,1,26842,0
25,26,46,M,11,22221,0
26,27,47,M,10,52021,0
27,28,40,F,2,58934,1
28,29,77,F,3,65528,1
29,30,54,M,19,61899,1

## 1. Exploración inicial
- ¿Cuántos registros y columnas tiene el dataset?
- ¿Qué tipos de datos tiene cada columna?
- ¿Existen valores atípicos evidentes en alguna variable numérica?

In [3]:
len(df)

30

In [4]:
print(df.dtypes)

id_paciente           int64
edad                  int64
genero                  str
dias_hospitalizado    int64
costo_tratamiento     int64
reingreso_30_dias     int64
dtype: object

In [5]:
df.describe()

,id_paciente,edad,dias_hospitalizado,costo_tratamiento,reingreso_30_dias
count,30.000000,30.000000,30.000000,30.000000,30.000000
mean,15.500000,52.233333,9.600000,39965.433333,0.366667
std,8.803408,19.141368,5.690888,20511.870433,0.490133
min,1.000000,19.000000,1.000000,5408.000000,0.000000
25%,8.250000,40.250000,3.500000,23500.250000,0.000000
50%,15.500000,54.500000,10.000000,33868.500000,0.000000
75%,22.750000,69.750000,13.750000,59061.500000,1.000000
max,30.000000,79.000000,19.000000,77751.000000,1.000000

In [6]:
import plotly.express as px

fig = px.box(
    df, 
    y = 'reingreso_30_dias'
)

fig.show()

## 2. Calidad de datos
- Verifica si existen valores nulos.
- ¿Qué columnas serían críticas para un análisis y no deberían tener valores faltantes?

In [7]:
df.isna().sum()

id_paciente           0
edad                  0
genero                0
dias_hospitalizado    0
costo_tratamiento     0
reingreso_30_dias     0
dtype: int64

## 3. Análisis descriptivo
- Calcula estadísticas básicas de edad, días hospitalizado y costo del tratamiento.
- ¿Qué variable presenta mayor dispersión?

In [8]:
df[['edad', 'dias_hospitalizado', 'costo_tratamiento']].describe()

            edad  dias_hospitalizado  costo_tratamiento
count  30.000000           30.000000          30.000000
mean   52.233333            9.600000       39965.433333
std    19.141368            5.690888       20511.870433
min    19.000000            1.000000        5408.000000
25%    40.250000            3.500000       23500.250000
50%    54.500000           10.000000       33868.500000
75%    69.750000           13.750000       59061.500000
max    79.000000           19.000000       77751.000000

In [14]:
df[['edad', 'dias_hospitalizado', 'costo_tratamiento']].std().sort_values(ascending=False)

costo_tratamiento     20511.870433
edad                     19.141368
dias_hospitalizado        5.690888
dtype: float64

## 4. Segmentación
- Propón una forma de segmentar a los pacientes según su costo de tratamiento.
- ¿Qué criterio usarías para definir pacientes de alto costo?

In [15]:
df['costo_tratamiento'].describe()

count       30.000000
mean     39965.433333
std      20511.870433
min       5408.000000
25%      23500.250000
50%      33868.500000
75%      59061.500000
max      77751.000000
Name: costo_tratamiento, dtype: float64

In [16]:
def segmentar_costo(costo_tratamiento):
    if costo_tratamiento <= 57150.500000:
        res = 'bajo'
        return res
    elif costo_tratamiento <= 64535.750000:
        res = 'medio'
        return res
    else:
        res = 'alto'
        return res


df['segmento_costo'] = df['costo_tratamiento'].apply(segmentar_costo)
df

,id_paciente,edad,genero,dias_hospitalizado,costo_tratamiento,reingreso_30_dias,segmento_costo
0,1,25,M,2,72971,0,alto
1,2,75,F,5,43590,0,bajo
2,3,74,M,14,22379,0,bajo
3,4,25,F,15,30350,1,bajo
4,5,19,M,13,65172,1,alto
5,6,65,F,18,65709,1,alto
6,7,73,M,13,28499,0,bajo
7,8,70,M,10,59259,1,medio
8,9,57,M,13,34741,0,bajo
9,10,49,M,3,22848,0,bajo
10,11,58,M,1,54924,0,bajo
11,12,74,F,14,25457,0,bajo
12,13,64,M,16,77751,0,alto
13,14,55,M,13,27221,0,bajo
14,15,42,F,16,32996,1,bajo
15,16,79,F,8,16435,0,bajo
16,17,41,F,10,5408,0,bajo
17,18,20,F,10,41170,0,bajo
18,19,28,F,10,28614,1,bajo
19,20,76,M,8,13140,0,bajo
20,21,69,F,11,17366,0,bajo
21,22,30,M,1,53320,0,bajo
22,23,46,F,1,59104,1,medio
23,24,28,F,17,13094,1,bajo
24,25,61,F,1,26842,0,bajo
25,26,46,M,11,22221,0,bajo
26,27,47,M,10,52021,0,bajo
27,28,40,F,2,58934,1,medio
28,29,77,F,3,65528,1,alto
29,30,54,M,19,61899,1,medio

In [17]:
df[df['segmento_costo'] == 'bajo']

,id_paciente,edad,genero,dias_hospitalizado,costo_tratamiento,reingreso_30_dias,segmento_costo
1,2,75,F,5,43590,0,bajo
2,3,74,M,14,22379,0,bajo
3,4,25,F,15,30350,1,bajo
6,7,73,M,13,28499,0,bajo
8,9,57,M,13,34741,0,bajo
9,10,49,M,3,22848,0,bajo
10,11,58,M,1,54924,0,bajo
11,12,74,F,14,25457,0,bajo
13,14,55,M,13,27221,0,bajo
14,15,42,F,16,32996,1,bajo
15,16,79,F,8,16435,0,bajo
16,17,41,F,10,5408,0,bajo
17,18,20,F,10,41170,0,bajo
18,19,28,F,10,28614,1,bajo
19,20,76,M,8,13140,0,bajo
20,21,69,F,11,17366,0,bajo
21,22,30,M,1,53320,0,bajo
23,24,28,F,17,13094,1,bajo
24,25,61,F,1,26842,0,bajo
25,26,46,M,11,22221,0,bajo
26,27,47,M,10,52021,0,bajo

## 5. KPI del sector salud
- Define un KPI que permita evaluar la eficiencia hospitalaria: ¿Qué tan rápido se resuelven los casos sin que el paciente vuelva al hospital?
- Explica qué variables del dataset usarías para calcularlo.

In [18]:
df

,id_paciente,edad,genero,dias_hospitalizado,costo_tratamiento,reingreso_30_dias,segmento_costo
0,1,25,M,2,72971,0,alto
1,2,75,F,5,43590,0,bajo
2,3,74,M,14,22379,0,bajo
3,4,25,F,15,30350,1,bajo
4,5,19,M,13,65172,1,alto
5,6,65,F,18,65709,1,alto
6,7,73,M,13,28499,0,bajo
7,8,70,M,10,59259,1,medio
8,9,57,M,13,34741,0,bajo
9,10,49,M,3,22848,0,bajo
10,11,58,M,1,54924,0,bajo
11,12,74,F,14,25457,0,bajo
12,13,64,M,16,77751,0,alto
13,14,55,M,13,27221,0,bajo
14,15,42,F,16,32996,1,bajo
15,16,79,F,8,16435,0,bajo
16,17,41,F,10,5408,0,bajo
17,18,20,F,10,41170,0,bajo
18,19,28,F,10,28614,1,bajo
19,20,76,M,8,13140,0,bajo
20,21,69,F,11,17366,0,bajo
21,22,30,M,1,53320,0,bajo
22,23,46,F,1,59104,1,medio
23,24,28,F,17,13094,1,bajo
24,25,61,F,1,26842,0,bajo
25,26,46,M,11,22221,0,bajo
26,27,47,M,10,52021,0,bajo
27,28,40,F,2,58934,1,medio
28,29,77,F,3,65528,1,alto
29,30,54,M,19,61899,1,medio

In [31]:
#df['dias_hospitalizado'].mean()

df_rapido = df[df['dias_hospitalizado'] < 10]


df_sinreingreso_rapido =  df_rapido[df_rapido['reingreso_30_dias'] == 0]
df_sinreingreso_rapido

#df_sinreingreso_rapido['dias_hospitalizado'].mean()

,id_paciente,edad,genero,dias_hospitalizado,costo_tratamiento,reingreso_30_dias,segmento_costo
0,1,25,M,2,72971,0,alto
1,2,75,F,5,43590,0,bajo
9,10,49,M,3,22848,0,bajo
10,11,58,M,1,54924,0,bajo
15,16,79,F,8,16435,0,bajo
19,20,76,M,8,13140,0,bajo
21,22,30,M,1,53320,0,bajo
24,25,61,F,1,26842,0,bajo

## 6. Visualización
- ¿Qué tipo de gráfica usarías para analizar la relación entre días hospitalizado y costo del tratamiento?
- ¿Qué insight de negocio o clínico podrías obtener de esa visualización?

In [52]:
df

,id_paciente,edad,genero,dias_hospitalizado,costo_tratamiento,reingreso_30_dias,segmento_costo
0,1,25,M,2,72971,0,alto
1,2,75,F,5,43590,0,bajo
2,3,74,M,14,22379,0,bajo
3,4,25,F,15,30350,1,bajo
4,5,19,M,13,65172,1,alto
5,6,65,F,18,65709,1,alto
6,7,73,M,13,28499,0,bajo
7,8,70,M,10,59259,1,medio
8,9,57,M,13,34741,0,bajo
9,10,49,M,3,22848,0,bajo
10,11,58,M,1,54924,0,bajo
11,12,74,F,14,25457,0,bajo
12,13,64,M,16,77751,0,alto
13,14,55,M,13,27221,0,bajo
14,15,42,F,16,32996,1,bajo
15,16,79,F,8,16435,0,bajo
16,17,41,F,10,5408,0,bajo
17,18,20,F,10,41170,0,bajo
18,19,28,F,10,28614,1,bajo
19,20,76,M,8,13140,0,bajo
20,21,69,F,11,17366,0,bajo
21,22,30,M,1,53320,0,bajo
22,23,46,F,1,59104,1,medio
23,24,28,F,17,13094,1,bajo
24,25,61,F,1,26842,0,bajo
25,26,46,M,11,22221,0,bajo
26,27,47,M,10,52021,0,bajo
27,28,40,F,2,58934,1,medio
28,29,77,F,3,65528,1,alto
29,30,54,M,19,61899,1,medio

In [77]:
import plotly.express as px

fig1 = px.bar(
    df,
    x= 'dias_hospitalizado',
    y='costo_tratamiento',
    color='segmento_costo',
    color_discrete_map={
                 'alto': "#EF553B",
                 'medio' : '#FECB52',
                 'bajo': "#00CC96"
                 
             },
    template='plotly_dark',
    title='Relación días hospitalizado y costo del tratamiento',
    labels={
        'costo_tratamiento' : 'Costo del tratamiento',
        'segmento_costo' : 'Costo por segmento',
        'dias_hospitalizado' : 'Dias hospitalizado',
        'alto' : 'alto costo'
    },
    category_orders={"segmento_costo": ["alto", "medio", "bajo"]}
    )

fig1.show()