# Entrenamiento 2

**Análisis de Datos – Sector Salud**

En este ejercicio trabajarás con un dataset ficticio del sector salud. Sigue las instrucciones y responde las preguntas planteadas. No incluyas las respuestas en este archivo.

In [12]:
import pandas as pd
import numpy as np

# Dataset ficticio de pacientes
data = {
    "id_paciente": range(1, 31),
    "edad": np.random.randint(18, 80, 30),
    "genero": np.random.choice(["F", "M"], 30),
    "dias_hospitalizado": np.random.randint(1, 20, 30),
    "costo_tratamiento": np.random.randint(5000, 80000, 30),
    "reingreso_30_dias": np.random.choice([0, 1], 30)
}

df = pd.DataFrame(data)
df

,id_paciente,edad,genero,dias_hospitalizado,costo_tratamiento,reingreso_30_dias
0,1,73,F,2,57170,1
1,2,53,F,8,64014,1
2,3,43,M,19,34156,1
3,4,73,F,8,72887,0
4,5,78,F,1,23456,0
5,6,26,M,5,23806,1
6,7,76,M,7,15317,1
7,8,57,F,19,46134,1
8,9,60,F,10,53387,0
9,10,78,M,5,23288,1
10,11,52,M,2,6595,1
11,12,52,M,3,21119,0
12,13,64,M,19,35529,0
13,14,78,M,3,50508,0
14,15,79,F,13,33641,1
15,16,65,F,4,30886,1
16,17,22,F,15,71834,0
17,18,67,F,16,38598,1
18,19,73,F,6,32417,1
19,20,23,M,1,17420,0
20,21,36,F,19,65432,0
21,22,47,F,10,29218,1
22,23,28,M,19,72207,0
23,24,26,F,3,53211,0
24,25,23,F,4,68208,0
25,26,79,M,7,39966,0
26,27,73,F,18,51172,1
27,28,36,M,14,35064,1
28,29,31,M,14,76725,1
29,30,72,M,9,60848,1

In [13]:
len(df)

30

In [14]:
print(df.dtypes)

id_paciente            int64
edad                   int64
genero                object
dias_hospitalizado     int64
costo_tratamiento      int64
reingreso_30_dias      int64
dtype: object

In [15]:
df.describe()

,id_paciente,edad,dias_hospitalizado,costo_tratamiento,reingreso_30_dias
count,30.000000,30.000000,30.000000,30.000000,30.000000
mean,15.500000,54.766667,9.433333,43473.766667,0.566667
std,8.803408,20.505144,6.333727,19721.004949,0.504007
min,1.000000,22.000000,1.000000,6595.000000,0.000000
25%,8.250000,36.000000,4.000000,29635.000000,0.000000
50%,15.500000,58.500000,8.000000,39282.000000,1.000000
75%,22.750000,73.000000,14.750000,59928.500000,1.000000
max,30.000000,79.000000,19.000000,76725.000000,1.000000

In [16]:
import plotly.express as px

fig = px.box(
    df, 
    y = 'reingreso_30_dias'
)

fig.show()

## 2. Calidad de datos
- Verifica si existen valores nulos.
- ¿Qué columnas serían críticas para un análisis y no deberían tener valores faltantes?

In [17]:
df.isna().sum()

id_paciente           0
edad                  0
genero                0
dias_hospitalizado    0
costo_tratamiento     0
reingreso_30_dias     0
dtype: int64

In [36]:
df.isnull().sum()

id_paciente           0
edad                  0
genero                0
dias_hospitalizado    0
costo_tratamiento     0
reingreso_30_dias     0
segmento_costo        0
dtype: int64

## 3. Análisis descriptivo
- Calcula estadísticas básicas de edad, días hospitalizado y costo del tratamiento.
- ¿Qué variable presenta mayor dispersión?

In [18]:
df[['edad', 'dias_hospitalizado', 'costo_tratamiento']].describe()

            edad  dias_hospitalizado  costo_tratamiento
count  30.000000           30.000000          30.000000
mean   54.766667            9.433333       43473.766667
std    20.505144            6.333727       19721.004949
min    22.000000            1.000000        6595.000000
25%    36.000000            4.000000       29635.000000
50%    58.500000            8.000000       39282.000000
75%    73.000000           14.750000       59928.500000
max    79.000000           19.000000       76725.000000

In [19]:
df[['edad', 'dias_hospitalizado', 'costo_tratamiento']].std().sort_values(ascending=False)

costo_tratamiento     19721.004949
edad                     20.505144
dias_hospitalizado        6.333727
dtype: float64

## 4. Segmentación
- Propón una forma de segmentar a los pacientes según su costo de tratamiento.
- ¿Qué criterio usarías para definir pacientes de alto costo?

In [20]:
df['costo_tratamiento'].describe()

count       30.000000
mean     43473.766667
std      19721.004949
min       6595.000000
25%      29635.000000
50%      39282.000000
75%      59928.500000
max      76725.000000
Name: costo_tratamiento, dtype: float64

In [40]:
q1 = df['costo_tratamiento'].quantile(0.25)
q3 = df['costo_tratamiento'].quantile(0.75)

def segmentar_costo(costo_tratamiento):
    if costo_tratamiento <= q1:
        res = 'bajo'
        return res
    elif costo_tratamiento <= q3:
        res = 'medio'
        return res
    else:
        res = 'alto'
        return res


df['segmento_costo'] = df['costo_tratamiento'].apply(segmentar_costo)
df
#print(q1)

,id_paciente,edad,genero,dias_hospitalizado,costo_tratamiento,reingreso_30_dias,segmento_costo
0,1,73,F,2,57170,1,medio
1,2,53,F,8,64014,1,alto
2,3,43,M,19,34156,1,medio
3,4,73,F,8,72887,0,alto
4,5,78,F,1,23456,0,bajo
5,6,26,M,5,23806,1,bajo
6,7,76,M,7,15317,1,bajo
7,8,57,F,19,46134,1,medio
8,9,60,F,10,53387,0,medio
9,10,78,M,5,23288,1,bajo
10,11,52,M,2,6595,1,bajo
11,12,52,M,3,21119,0,bajo
12,13,64,M,19,35529,0,medio
13,14,78,M,3,50508,0,medio
14,15,79,F,13,33641,1,medio
15,16,65,F,4,30886,1,medio
16,17,22,F,15,71834,0,alto
17,18,67,F,16,38598,1,medio
18,19,73,F,6,32417,1,medio
19,20,23,M,1,17420,0,bajo
20,21,36,F,19,65432,0,alto
21,22,47,F,10,29218,1,bajo
22,23,28,M,19,72207,0,alto
23,24,26,F,3,53211,0,medio
24,25,23,F,4,68208,0,alto
25,26,79,M,7,39966,0,medio
26,27,73,F,18,51172,1,medio
27,28,36,M,14,35064,1,medio
28,29,31,M,14,76725,1,alto
29,30,72,M,9,60848,1,alto

In [43]:
df[df['segmento_costo'] == 'alto']

,id_paciente,edad,genero,dias_hospitalizado,costo_tratamiento,reingreso_30_dias,segmento_costo
1,2,53,F,8,64014,1,alto
3,4,73,F,8,72887,0,alto
16,17,22,F,15,71834,0,alto
20,21,36,F,19,65432,0,alto
22,23,28,M,19,72207,0,alto
24,25,23,F,4,68208,0,alto
28,29,31,M,14,76725,1,alto
29,30,72,M,9,60848,1,alto

## 5. KPI del sector salud
- Define un KPI que permita evaluar la eficiencia hospitalaria: ¿Qué tan rápido se resuelven los casos sin que el paciente vuelva al hospital?
- Explica qué variables del dataset usarías para calcularlo.

In [24]:
df

,id_paciente,edad,genero,dias_hospitalizado,costo_tratamiento,reingreso_30_dias,segmento_costo
0,1,73,F,2,57170,1,medio
1,2,53,F,8,64014,1,medio
2,3,43,M,19,34156,1,bajo
3,4,73,F,8,72887,0,alto
4,5,78,F,1,23456,0,bajo
5,6,26,M,5,23806,1,bajo
6,7,76,M,7,15317,1,bajo
7,8,57,F,19,46134,1,bajo
8,9,60,F,10,53387,0,bajo
9,10,78,M,5,23288,1,bajo
10,11,52,M,2,6595,1,bajo
11,12,52,M,3,21119,0,bajo
12,13,64,M,19,35529,0,bajo
13,14,78,M,3,50508,0,bajo
14,15,79,F,13,33641,1,bajo
15,16,65,F,4,30886,1,bajo
16,17,22,F,15,71834,0,alto
17,18,67,F,16,38598,1,bajo
18,19,73,F,6,32417,1,bajo
19,20,23,M,1,17420,0,bajo
20,21,36,F,19,65432,0,alto
21,22,47,F,10,29218,1,bajo
22,23,28,M,19,72207,0,alto
23,24,26,F,3,53211,0,bajo
24,25,23,F,4,68208,0,alto
25,26,79,M,7,39966,0,bajo
26,27,73,F,18,51172,1,bajo
27,28,36,M,14,35064,1,bajo
28,29,31,M,14,76725,1,alto
29,30,72,M,9,60848,1,medio

In [25]:
#df['dias_hospitalizado'].mean()

df_rapido = df[df['dias_hospitalizado'] < 10]


df_sinreingreso_rapido =  df_rapido[df_rapido['reingreso_30_dias'] == 0]
df_sinreingreso_rapido

#df_sinreingreso_rapido['dias_hospitalizado'].mean()

,id_paciente,edad,genero,dias_hospitalizado,costo_tratamiento,reingreso_30_dias,segmento_costo
3,4,73,F,8,72887,0,alto
4,5,78,F,1,23456,0,bajo
11,12,52,M,3,21119,0,bajo
13,14,78,M,3,50508,0,bajo
19,20,23,M,1,17420,0,bajo
23,24,26,F,3,53211,0,bajo
24,25,23,F,4,68208,0,alto
25,26,79,M,7,39966,0,bajo

## 6. Visualización
- ¿Qué tipo de gráfica usarías para analizar la relación entre días hospitalizado y costo del tratamiento?
- ¿Qué insight de negocio o clínico podrías obtener de esa visualización?

In [ ]:
df

In [44]:
import plotly.express as px

fig1 = px.scatter(
    df,
    x= 'dias_hospitalizado',
    y='costo_tratamiento',
    color='segmento_costo',
    color_discrete_map={
                 'alto': "#EF553B",
                 'medio' : '#FECB52',
                 'bajo': "#00CC96"
                 
             },
    template='plotly_dark',
    title='Relación días hospitalizado y costo del tratamiento',
    labels={
        'costo_tratamiento' : 'Costo del tratamiento',
        'segmento_costo' : 'Costo por segmento',
        'dias_hospitalizado' : 'Dias hospitalizado',
        'alto' : 'alto costo'
    },
    category_orders={"segmento_costo": ["alto", "medio", "bajo"]},
    size = 'edad'
    )

fig1.update_xaxes(
    range=[0, 20],      
    dtick=1             
)

fig1.show()