## REPORTE DE ENTRENAMIENTO 2

Esta práctica tiene como proposito hacer un análisis de sobre un data set ficticio de un hospital con diferentes datos de pacientes. Al igual del entrenamiento anterior, se hicierón análisis con la intención de respender preguntas y ejercicios que se fuerón pidiendo.  

En este reporte de práctica iré explicando como lo fui resolviendo de forma general, para ver la a detalle de las consultas, bloques de codigo que fui usando dejaré un link para el repositorio en GitHub.

<a href="https://github.com/RodrigoGarcia96/entrenamientos/tree/main/practica_2" target="_blank">Enlace: Práctica_2</a>

Se presenta un data set ficticio llamado <font color="green">pacientes</font>, en esta ocación no viene de un archivo csv, más bien viene de detrminar las columnas que tendrá, y asignarle valores aleatorios estableciendo un rango. Con la finalidad de mostrar el mismo data frame, hare el df que me generó a mi, para que sea el mismo ya que si pongo tal cual la linea de codigo, generará datos diferentes ya que este usa valores aleatorios.

In [3]:
import pandas as pd

data = {
    "id_paciente": [1,2,3,4,5,6,7,8,9,10,
                    11,12,13,14,15,16,17,18,19,20,
                    21,22,23,24,25,26,27,28,29,30],
    
    "edad": [73,53,43,73,78,26,76,57,60,78,
             52,52,64,78,79,65,22,67,73,23,
             36,47,28,26,23,79,73,36,31,72],
    
    "genero": ["F","F","M","F","F","M","M","F","F","M",
               "M","M","M","M","F","F","F","F","F","M",
               "F","F","M","F","F","M","F","M","M","M"],
    
    "dias_hospitalizado": [2,8,19,8,1,5,7,19,10,5,
                           2,3,19,3,13,4,15,16,6,1,
                           19,10,19,3,4,7,18,14,14,9],
    
    "costo_tratamiento": [57170,64014,34156,72887,23456,23806,15317,46134,53387,23288,
                          6595,21119,35529,50508,33641,30886,71834,38598,32417,17420,
                          65432,29218,72207,53211,68208,39966,51172,35064,76725,60848],
    
    "reingreso_30_dias": [1,1,1,0,0,1,1,1,0,1,
                          1,0,0,0,1,1,0,1,1,0,
                          0,1,0,0,0,0,1,1,1,1]
}

df = pd.DataFrame(data)

df

,id_paciente,edad,genero,dias_hospitalizado,costo_tratamiento,reingreso_30_dias
0,1,73,F,2,57170,1
1,2,53,F,8,64014,1
2,3,43,M,19,34156,1
3,4,73,F,8,72887,0
4,5,78,F,1,23456,0
5,6,26,M,5,23806,1
6,7,76,M,7,15317,1
7,8,57,F,19,46134,1
8,9,60,F,10,53387,0
9,10,78,M,5,23288,1
10,11,52,M,2,6595,1
11,12,52,M,3,21119,0
12,13,64,M,19,35529,0
13,14,78,M,3,50508,0
14,15,79,F,13,33641,1
15,16,65,F,4,30886,1
16,17,22,F,15,71834,0
17,18,67,F,16,38598,1
18,19,73,F,6,32417,1
19,20,23,M,1,17420,0
20,21,36,F,19,65432,0
21,22,47,F,10,29218,1
22,23,28,M,19,72207,0
23,24,26,F,3,53211,0
24,25,23,F,4,68208,0
25,26,79,M,7,39966,0
26,27,73,F,18,51172,1
27,28,36,M,14,35064,1
28,29,31,M,14,76725,1
29,30,72,M,9,60848,1

## Sección 1

En esta sección se pide que muestre el numero de datos que tiene el df y muestre los tipos de datos que contiene.

In [4]:
len(df)

30

In [5]:
print(df.dtypes)

id_paciente            int64
edad                   int64
genero                object
dias_hospitalizado     int64
costo_tratamiento      int64
reingreso_30_dias      int64
dtype: object

Luego pide que revise si hay datos atípicos o <font color="blue">Outliers</font>, para lo que decido mostrar los cuartiles para ver si en los datos hay valores muy diferentes, a lo que veo que no.

In [6]:
df.describe()

,id_paciente,edad,dias_hospitalizado,costo_tratamiento,reingreso_30_dias
count,30.000000,30.000000,30.000000,30.000000,30.000000
mean,15.500000,54.766667,9.433333,43473.766667,0.566667
std,8.803408,20.505144,6.333727,19721.004949,0.504007
min,1.000000,22.000000,1.000000,6595.000000,0.000000
25%,8.250000,36.000000,4.000000,29635.000000,0.000000
50%,15.500000,58.500000,8.000000,39282.000000,1.000000
75%,22.750000,73.000000,14.750000,59928.500000,1.000000
max,30.000000,79.000000,19.000000,76725.000000,1.000000

## Sección 2

Aqui me pide revise si existen valores nulos o valores vacios, y hace una pregunta sobre las columnas serían importantes para hacer un análisis a fondo.

In [7]:
df.isna().sum()

id_paciente           0
edad                  0
genero                0
dias_hospitalizado    0
costo_tratamiento     0
reingreso_30_dias     0
dtype: int64

In [8]:
df.isnull().sum()

id_paciente           0
edad                  0
genero                0
dias_hospitalizado    0
costo_tratamiento     0
reingreso_30_dias     0
dtype: int64

Por lo que vemos es que no hay razón para hacer una revisión a fondo de alguna columna del df ya que no hay algo extraño, tampoco tiene valores nulos ni vacios.

## Sección 3

- Calcula estadísticas básicas de edad, días hospitalizado y costo del tratamiento.
- ¿Qué variable presenta mayor dispersión?

Para resolver esta parte lo que decido hacer es que en el mismo df solamente muestro edad, ías hospitalizado y costo del tratamiento y aplico la función "describe()"

In [ ]:
df[['edad', 'dias_hospitalizado', 'costo_tratamiento']].describe()

            edad  dias_hospitalizado  costo_tratamiento
count  30.000000           30.000000          30.000000
mean   54.766667            9.433333       43473.766667
std    20.505144            6.333727       19721.004949
min    22.000000            1.000000        6595.000000
25%    36.000000            4.000000       29635.000000
50%    58.500000            8.000000       39282.000000
75%    73.000000           14.750000       59928.500000
max    79.000000           19.000000       76725.000000

Para la parte de que pide cual es la variable que presenta mayor dispersión uso ".std()" para calcular la desviación estandar, luego ordenarlos del mayor al menor y vemos que la que tiene más dispersión es la variable de "costo_tratamiento"

In [ ]:
df[['edad', 'dias_hospitalizado', 'costo_tratamiento']].std().sort_values(ascending=False)

costo_tratamiento     19721.004949
edad                     20.505144
dias_hospitalizado        6.333727
dtype: float64

## Sección 4

- Propón una forma de segmentar a los pacientes según su costo de tratamiento.
- ¿Qué criterio usarías para definir pacientes de alto costo?


Para resolver la primera parte, lo que decido es calcular los cuartiles para segregarlos de alto costo, medio costo y bajo costo de la variable "costo_tratamiento". Los cuartiles me ayudan a ver los valores de 25%, 50% y 75% para su clasificación usando la variable de "costo_tratamiento".

In [11]:
df['costo_tratamiento'].describe()

count       30.000000
mean     43473.766667
std      19721.004949
min       6595.000000
25%      29635.000000
50%      39282.000000
75%      59928.500000
max      76725.000000
Name: costo_tratamiento, dtype: float64

In [17]:
q1 = df['costo_tratamiento'].quantile(0.25)
q3 = df['costo_tratamiento'].quantile(0.75)

def segmentar_costo(costo_tratamiento):
    if costo_tratamiento <= q1:
        res = 'bajo'
        return res
    elif costo_tratamiento <= q3:
        res = 'medio'
        return res
    else:
        res = 'alto'
        return res


df['segmento_costo'] = df['costo_tratamiento'].apply(segmentar_costo)
df.head()
#print(q1)

,id_paciente,edad,genero,dias_hospitalizado,costo_tratamiento,reingreso_30_dias,segmento_costo
0,1,73,F,2,57170,1,medio
1,2,53,F,8,64014,1,alto
2,3,43,M,19,34156,1,medio
3,4,73,F,8,72887,0,alto
4,5,78,F,1,23456,0,bajo

## Sección 5

- Define un KPI que permita evaluar la eficiencia hospitalaria.
- Explica qué variables del dataset usarías para calcularlo.

Para responder esto propongo esta pregunta para el KPI: ¿Qué tan rápido se resuelven los casos sin que el paciente vuelva al hospital?

Contando con esta pegunta se entiende que se deben de usar 2 variables para poderla responder dias_hopitalizado y reingreso_30_dias. 

Primero saco el promedio de días hospitalizado.

In [18]:
df['dias_hospitalizado'].mean()

np.float64(9.433333333333334)

Lo que nos da como resultado 9 y deahí filto de esos pacientes, determinar los que no tuvierón un reingreso

In [20]:
#df['dias_hospitalizado'].mean()

df_rapido = df[df['dias_hospitalizado'] < 10]


df_sin_reingreso_rapido =  df_rapido[df_rapido['reingreso_30_dias'] == 0]
df_sin_reingreso_rapido

,id_paciente,edad,genero,dias_hospitalizado,costo_tratamiento,reingreso_30_dias,segmento_costo
3,4,73,F,8,72887,0,alto
4,5,78,F,1,23456,0,bajo
11,12,52,M,3,21119,0,bajo
13,14,78,M,3,50508,0,medio
19,20,23,M,1,17420,0,bajo
23,24,26,F,3,53211,0,medio
24,25,23,F,4,68208,0,alto
25,26,79,M,7,39966,0,medio

## Sección 6 

- ¿Qué tipo de gráfica usarías para analizar la relación entre días hospitalizado y costo del tratamiento?
- ¿Qué insight de negocio o clínico podrías obtener de esa visualización?

Yo use un gráfico de burbujas para ver la relación entre los días que estaban en el hospital y el costo del tratamiento, también quería ver si los pacientes más grandes eran los que resibían los tratamientos más costosos, a lo que hago la siguiente visualización.

In [25]:
import plotly.express as px
import plotly.io as pio
pio.renderers.default = "notebook_connected"

fig1 = px.scatter(
    df,
    x= 'dias_hospitalizado',
    y='costo_tratamiento',
    color='segmento_costo',
    color_discrete_map={
                 'alto': "#EF553B",
                 'medio' : '#FECB52',
                 'bajo': "#00CC96"
                 
             },
    template='plotly_dark',
    title='Relación días hospitalizado y costo del tratamiento',
    labels={
        'costo_tratamiento' : 'Costo del tratamiento',
        'segmento_costo' : 'Costo por segmento',
        'dias_hospitalizado' : 'Dias hospitalizado',
        'alto' : 'alto costo'
    },
    category_orders={"segmento_costo": ["alto", "medio", "bajo"]},
    size = 'edad'
    )

fig1.update_xaxes(
    range=[0, 20],      
    dtick=1             
)

fig1.show()

Aqui podemos ver que a mayor días que pasan, incrementa el costo del tratamiento.